### PR TITLE
Feat: Enhance homepage and navbar

### PR DESCRIPTION
**Pull request by blackdreamer15**
This pull request includes several changes to the navigation bar and the home page to enhance the user interface and user experience. The main changes involve adding animations using the `framer-motion` library, fixing typos in the `Props` interface, and refactoring the code for better readability and maintainability.

### Enhancements to the navigation bar:

* Added `framer-motion` animations to the navigation bar for smoother transitions and interactions. (`src/components/shared/nav.tsx`)
* Fixed typos in the `Props` interface, changing `undelinecolor` to `underlineColor`. (`src/components/shared/nav.tsx`)
* Updated the `NavBar` component usage to reflect the corrected `Props` interface. (`src/layout/parallax-page.layout.tsx`, `src/pages/share-memory.tsx`) [[1]](diffhunk://#diff-930b176e24b9f352a950c6a44b8ac7a03ab3486e57283c818315110e1cc79012L11-R11) [[2]](diffhunk://#diff-9de1a96ee7cdd8d0a3911696134b5fcbd153d8d4c037a041219775d7a6e61377L83-R83)

### Enhancements to the home page:

* Added typewriter animation to the title and name text on the home page using `framer-motion`. (`src/pages/Home.tsx`) [[1]](diffhunk://#diff-e41191ca0fedc3d7c9cfce4db24a281797128fbd57681267d583ba9e01069a0eR4-R30) [[2]](diffhunk://#diff-e41191ca0fedc3d7c9cfce4db24a281797128fbd57681267d583ba9e01069a0eL19-R90)

### CODE REVIEW

**Comment by blackdreamer15** [comment]
@frimpsss @blackprince001, take a look at the homepage and let me know your thoughts. I added a cool effect to Jojo's name—when you hover over it, the fill disappears, leaving just the strokes.

What do you think about reversing it? It could start without the fill, and when you hover, it fills in. Would that be better?

**Comment by blackprince001** [comment]
I like navbar and the concept very much. Could increase the animation speed of the letters? the rendering keeps breaking for some reason and I believe this to be an edge for other devices that would encounter the page?

@blackdreamer15

**Comment by blackdreamer15** [comment]
> I like navbar and the concept very much. Could increase the animation speed of the letters? the rendering keeps breaking for some reason and I believe this to be an edge for other devices that would encounter the page?
> 
> @blackdreamer15

What do you think of the recent change.
@blackprince001

**Comment by blackprince001** [comment]
checking it out soon. will give feedback

**Review by blackprince001 — COMMENTED** [review]
I think this is a bit better. Merging. Thank you man

**Pull request merged**
